### ISSUE TITLE
[suggestion] add check and warn if player already added / removed

### ISSUE THREAD

**Issue by RedstoneFuture** [pop4959/LWCTrust#2]
Would you like add a check and a configurable message, if the player is already added to the list?

Example:
1. /trust add testuser1
2. /trust confirm
2. /trust add testuser1 --> + warn: "The player %n is already added."

Same for the remove action:

1. /trust list = empty oder "testuser1"
2. /ctrust remove testuser2 --> + warn: "The player %n is not in the list."

**Comment by pop4959** [comment]
I intentionally avoided such warnings to avoid being redundant, as the commands currently only send a message to the player if something changed.

e.g.:
`/trust add a b c` where a and c are already on the list -> sends message only about b
`/trust remove a b c` where no one is on the list -> need send nothing

I was trying to mimic how LWC's modify command sends message, in order to make things seem familiar, although it seems like modify just prints an added message regardless of whether they are already on the list or not. So maybe it should be changed to that instead?

**Comment by RedstoneFuture** [comment]
mmh, right ... I see what do you mean. But I think today it's normal to get a correct feedback based on the list-data. I think the most of all plugins have warnings for that. Can you add it in booth plugins? LWCX + LWTrust ? Or it's too complicated?

EDIT: Currently, you get a feedback for all added / removed player one by one. That's good!
I think at the best you make a simple check and send a message:

```
trust.add_error: "%s could not be removed."
trust.remove_error: "%s could not be added."

protection.interact.rights.register.player_error="Could not be added the player %name%."
protection.interact.rights.register.group_error="Could not be added the group %name%."
protection.interact.rights.register.region_error="Could not be added the region %name%."
protection.interact.rights.remove.player_error="Could not be removed the player %name%."
protection.interact.rights.remove.group_error="Could not be removed the group %name%."
protection.interact.rights.remove.region_error="Could not be removed the region %name%."
```

I think it's very helpful for the usability. Specifically for the complex /cpivate & /cmodify command.

Or what do you mean?

**Comment by pop4959** [comment]
I think I'll fix it so that the messages in Trust match more similarly with LWC. It's technically not difficult to add both, but it does make it more complicated. Users already expect the positive messages, and giving them a negative message (especially something like "could not be removed" or "could not be added") can make it seem like the plugin isn't working correctly when it is. More specifically, you're suggesting that this feedback be printed when things can/cannot be added because they already are/aren't on the list, not because they aren't able to be. I hope that makes sense. I understand that other plugins may work differently with errors, but all plugins are different. 😛

**Comment by RedstoneFuture** [comment]
ok ... yes, the warnings are not so important.

**Comment by pop4959** [comment]
I'm still glad we discussed it; there is always room for improvement!

**Comment by pop4959** [comment]
Latest version now prints feedback regardless of whether or not they were actually added or not (so same as LWC)
