### ISSUE TITLE
[Suggestion] Destroying secured blocks by players added to the trust list

### ISSUE THREAD

**Issue by XANT3R** [pop4959/LWCTrust#3]
Add the ability to destroy secured blocks by people added to the trust list.

Why? Because /cmodify nick adds the player to the block and allows you to destroy it, so blocking destroy by players  it on the trust list is pointless.

**Comment by pop4959** [comment]
Uh... not quite sure what you mean. Are you suggesting that `/cmodify` gives players the ability to destroy your protections? It actually does not, last I checked.

**Comment by XANT3R** [comment]
If someone is added to the trust, they should be able to to destroy my chests, I don't understand why this is blocked.

Yes, /cmodify for chests allows another player added to such protection to destroy it.

**Comment by kamil004** [comment]
example
If i make chest and add another player to my all lwc /trust add nick then another player can't destroy this chest.

**Comment by pop4959** [comment]
Trusted players have the same access as if you ran `/cmodify` for the player on every single one of your protections. If you are not the actual owner of the protection, even if you are modified to it, you cannot destroy that protection since it is not yours.

This is how it works in LWC and by extension also in LWC Trust.
