### ISSUE TITLE
More infos on the /trust list command

### ISSUE THREAD

**Issue by Majhinell** [pop4959/LWCTrust#5]
My suggestion is that when a player does the /trust list command, it should also tell him which player has added him in their trust list

**Comment by pop4959** [comment]
This isn't actually easy to do since the trust lists are stored per player so there is no reverse lookup unless you want to open every file and check every list for the player (which can get expensive on big servers). Hopefully the notifications are enough (plus players just telling each other if they are able to access each other's stuff).
