### ISSUE TITLE
[BUG] Two small problems related to LWCTrust

### ISSUE THREAD

**Issue by luoxiawuchen** [pop4959/LWCTrust#8]
1、command "/trust add <player>"  can be used by players themselves.
A player whose ID is test , Enter command "/trust add test" , The command will still be executed.

2、Players can add trusted players repeatedly, even if they have already added them once.

Two minor defects are harmless, but if they can be improved slightly, they may prevent some potential unsafe factors. Thanks for the patience of the author.

**Comment by pop4959** [comment]
As it turns out neither of these are bugs:

1. Trust commands are intended to be used by players. This only impacts their own trusted players (not for others).
2. Players are not actually added multiple times to trust, although you can type the player's name again and it is not an error.

If you have any other questions feel free to ask in the LWC channels on our [Discord server](https://discord.gg/PHpuzZS)!

**Comment by luoxiawuchen** [comment]
> As it turns out neither of these are bugs:
> 
> 1. Trust commands are intended to be used by players. This only impacts their own trusted players (not for others).
> 2. Players are not actually added multiple times to trust, although you can type the player's name again and it is not an error.
> 
> If you have any other questions feel free to ask in the LWC channels on our [Discord server](https://discord.gg/PHpuzZS)!

Ok , thank you for your patient reply.
