### ISSUE TITLE
About the group server

### ISSUE THREAD

**Issue by zfms4188** [pop4959/LWCTrust#9]
Do you have plans to update the functionality for group server synchronization? Or add an overload function to reread the file , thank you

**Comment by pop4959** [comment]
Hey, thanks for the feature request!

Unfortunately I have no plans to support anything like this in LWC Trust, especially since LWC doesn't itself either.

This add-on is also deprecated in favor of the trust functionality in Bolt. It may actually already be possible to "synchronize" this in Bolt, using the MySQL database option (although like with LWC, it isn't really intended for multi-server use). If not, I might consider it as a feature request there instead. But this sounds a bit niche, so no promises, I would need to hear what kind of use case this covers first.
